# Generated by Django 5.1.7 on 2025-09-16 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerScienceConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название концепции')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('difficulty', models.IntegerField(default=1, verbose_name='Сложность (от 1 до 5)')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Публикация')),
                ('image', models.ImageField(blank=True, null=True, upload_to='concept_images/%Y/%m/%d/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Концепция компьютерных наук',
                'verbose_name_plural': 'Концепции компьютерных наук',
                'ordering': ['-time_create'],
                'permissions': [('can_publish_concept', 'Может публиковать концепцию')],
            },
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Область науки')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание области')),
            ],
            options={
                'verbose_name': 'Область науки',
                'verbose_name_plural': 'Области науки',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
                ('slug', models.SlugField(unique=True, verbose_name='URL тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='ConceptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_technologies', models.TextField(blank=True, verbose_name='Ключевые технологии')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Предварительные условия')),
                ('estimated_learning_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Примерное время изучения (часы)')),
                ('concept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='cs.computerscienceconcept', verbose_name='Концепция')),
            ],
            options={
                'verbose_name': 'Детали концепции',
                'verbose_name_plural': 'Детали концепций',
            },
        ),
        migrations.AddField(
            model_name='computerscienceconcept',
            name='field_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='cs.fieldofstudy', verbose_name='Область науки'),
        ),
        migrations.AddField(
            model_name='computerscienceconcept',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='concepts', to='cs.tag', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='computerscienceconcept',
            index=models.Index(fields=['-time_create'], name='cs_computer_time_cr_f7812e_idx'),
        ),
    ]
