# Generated by Django 5.1.7 on 2025-09-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerScienceConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название концепции')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('difficulty', models.IntegerField(default=1, verbose_name='Сложность (от 1 до 5)')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Концепция компьютерных наук',
                'verbose_name_plural': 'Концепции компьютерных наук',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='cs_computer_time_cr_f7812e_idx')],
            },
        ),
    ]
