# Generated by Django 4.2.1 on 2025-09-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerscienceconcept',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='concept_images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
