# Generated by Django 4.2.1 on 2025-09-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0002_computerscienceconcept_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerscienceconcept',
            name='image',
        ),
    ]
